[package]
name = "tshake"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.5.0"
clap = { version = "4.5.4", features = ["derive"] }
toml = "0.8.12"
serde = { version = "1.0.201", features = ["derive"] }